FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

# Instalar las herramientas de SQL Server (sqlcmd y bcp)
RUN apt-get update && apt-get install -y curl gnupg2
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools

# Copia el archivo .sql al contenedor
COPY database.sh /docker-entrypoint-initdb.d/


